// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// devSVG_
bool devSVG_(std::string file, std::string bg_, int width, int height, int pointsize, bool standalone, int canvas_id);
RcppExport SEXP rvg_devSVG_(SEXP fileSEXP, SEXP bg_SEXP, SEXP widthSEXP, SEXP heightSEXP, SEXP pointsizeSEXP, SEXP standaloneSEXP, SEXP canvas_idSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type file(fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type bg_(bg_SEXP);
    Rcpp::traits::input_parameter< int >::type width(widthSEXP);
    Rcpp::traits::input_parameter< int >::type height(heightSEXP);
    Rcpp::traits::input_parameter< int >::type pointsize(pointsizeSEXP);
    Rcpp::traits::input_parameter< bool >::type standalone(standaloneSEXP);
    Rcpp::traits::input_parameter< int >::type canvas_id(canvas_idSEXP);
    __result = Rcpp::wrap(devSVG_(file, bg_, width, height, pointsize, standalone, canvas_id));
    return __result;
END_RCPP
}
// set_tracer_on
bool set_tracer_on(int dn);
RcppExport SEXP rvg_set_tracer_on(SEXP dnSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type dn(dnSEXP);
    __result = Rcpp::wrap(set_tracer_on(dn));
    return __result;
END_RCPP
}
// set_tracer_off
bool set_tracer_off(int dn);
RcppExport SEXP rvg_set_tracer_off(SEXP dnSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type dn(dnSEXP);
    __result = Rcpp::wrap(set_tracer_off(dn));
    return __result;
END_RCPP
}
// collect_id
Rcpp::IntegerVector collect_id(int dn);
RcppExport SEXP rvg_collect_id(SEXP dnSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type dn(dnSEXP);
    __result = Rcpp::wrap(collect_id(dn));
    return __result;
END_RCPP
}
// add_tooltip
bool add_tooltip(int dn, Rcpp::IntegerVector id, std::vector< std::string > str);
RcppExport SEXP rvg_add_tooltip(SEXP dnSEXP, SEXP idSEXP, SEXP strSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type dn(dnSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type id(idSEXP);
    Rcpp::traits::input_parameter< std::vector< std::string > >::type str(strSEXP);
    __result = Rcpp::wrap(add_tooltip(dn, id, str));
    return __result;
END_RCPP
}
// add_click_event
bool add_click_event(int dn, Rcpp::IntegerVector id, std::vector< std::string > str);
RcppExport SEXP rvg_add_click_event(SEXP dnSEXP, SEXP idSEXP, SEXP strSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type dn(dnSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type id(idSEXP);
    Rcpp::traits::input_parameter< std::vector< std::string > >::type str(strSEXP);
    __result = Rcpp::wrap(add_click_event(dn, id, str));
    return __result;
END_RCPP
}
// add_data_id
bool add_data_id(int dn, Rcpp::IntegerVector id, std::vector< std::string > data_id);
RcppExport SEXP rvg_add_data_id(SEXP dnSEXP, SEXP idSEXP, SEXP data_idSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type dn(dnSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type id(idSEXP);
    Rcpp::traits::input_parameter< std::vector< std::string > >::type data_id(data_idSEXP);
    __result = Rcpp::wrap(add_data_id(dn, id, data_id));
    return __result;
END_RCPP
}
