# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

DOCX_ <- function(file, bg_, width, height, pointsize, fontname_serif, fontname_sans, fontname_mono, fontname_symbol, editable, id, raster_prefix, next_rels_id, standalone) {
    .Call('rvg_DOCX_', PACKAGE = 'rvg', file, bg_, width, height, pointsize, fontname_serif, fontname_sans, fontname_mono, fontname_symbol, editable, id, raster_prefix, next_rels_id, standalone)
}

DSVG_ <- function(file, width, height, bg, pointsize, standalone, canvas_id, fontname_serif, fontname_sans, fontname_mono, fontname_symbol) {
    .Call('rvg_DSVG_', PACKAGE = 'rvg', file, width, height, bg, pointsize, standalone, canvas_id, fontname_serif, fontname_sans, fontname_mono, fontname_symbol)
}

set_tracer_on <- function(dn) {
    .Call('rvg_set_tracer_on', PACKAGE = 'rvg', dn)
}

set_tracer_off <- function(dn) {
    .Call('rvg_set_tracer_off', PACKAGE = 'rvg', dn)
}

collect_id <- function(dn) {
    .Call('rvg_collect_id', PACKAGE = 'rvg', dn)
}

add_attribute <- function(dn, id, str, name) {
    .Call('rvg_add_attribute', PACKAGE = 'rvg', dn, id, str, name)
}

add_tooltip <- function(dn, id, str) {
    .Call('rvg_add_tooltip', PACKAGE = 'rvg', dn, id, str)
}

add_click_event <- function(dn, id, str) {
    .Call('rvg_add_click_event', PACKAGE = 'rvg', dn, id, str)
}

add_data_id <- function(dn, id, data_id) {
    .Call('rvg_add_data_id', PACKAGE = 'rvg', dn, id, data_id)
}

PPTX_ <- function(file, bg_, width, height, offx, offy, pointsize, fontname_serif, fontname_sans, fontname_mono, fontname_symbol, editable, id, raster_prefix, next_rels_id, standalone) {
    .Call('rvg_PPTX_', PACKAGE = 'rvg', file, bg_, width, height, offx, offy, pointsize, fontname_serif, fontname_sans, fontname_mono, fontname_symbol, editable, id, raster_prefix, next_rels_id, standalone)
}

